from __future__ import annotations

from pathlib import Path
from typing import Any
import re

import cv2
import numpy as np

HEURISTIC_ACTION_NOTE = (
    "Toy pseudo-actions are generated by coarse motion_type rules and are not ground-truth odometry."
)
OPTICAL_FLOW_ACTION_NOTE = (
    "Pseudo-actions are estimated from video optical flow and are not ground-truth odometry."
)
EMPTY_ACTION_NOTE = "Actions are empty; no pseudo-action baseline was requested."
INSTRUCTION_ACTION_NOTE = (
    "Pseudo-actions are derived from language instructions and are not ground-truth odometry."
)

INSTRUCTION_KEYWORDS = {
    "forward": ["move forward", "go straight", "forward", "前进", "前進", "向前", "直走", "直行"],
    "left_turn": ["turn left", "left", "左转", "左轉", "向左"],
    "right_turn": ["turn right", "right", "右转", "右轉", "向右"],
    "stop": ["stop", "停止", "停"],
    "up": ["go up", "up", "上楼", "上樓", "上坡", "向上"],
    "down": ["go down", "down", "下楼", "下樓", "下坡", "向下"],
}


def estimate_empty_actions() -> list[dict[str, float]]:
    """Return no actions for runs that should not create pseudo-labels."""
    return []


def estimate_heuristic_actions(
    motion_type: str,
    clip_duration: float,
    step_seconds: float = 1.0,
) -> list[dict[str, float]]:
    """Generate toy dx/dy/dyaw pseudo-actions from a coarse motion type.

    This is a toy pseudo-action baseline for dataset prototyping only. It is
    not real UAV odometry and should not be treated as ground-truth trajectory
    data.
    """
    if clip_duration <= 0:
        return []

    normalized_motion_type = (motion_type or "unknown").lower()
    rule = _motion_rule(normalized_motion_type)
    action_count = max(1, int(round(clip_duration / step_seconds)))

    actions: list[dict[str, float]] = []
    for i in range(action_count):
        t = min(round(i * step_seconds, 3), round(clip_duration, 3))
        actions.append(
            {
                "t": t,
                "dx": rule["dx"],
                "dy": rule["dy"],
                "dyaw": rule["dyaw"],
            }
        )

    final_t = round(clip_duration, 3)
    if actions[-1]["t"] < final_t:
        actions.append({"t": final_t, "dx": rule["dx"], "dy": rule["dy"], "dyaw": rule["dyaw"]})

    return actions


def parse_instruction_actions(instruction: str) -> list[dict[str, Any]]:
    """Parse high-level actions from Chinese or English instruction text."""
    if not instruction:
        return []

    lowered = instruction.lower()
    matches: list[dict[str, Any]] = []
    for action_type, keywords in INSTRUCTION_KEYWORDS.items():
        for keyword in keywords:
            for start, end in _find_keyword_spans(lowered, keyword):
                matches.append(
                    {
                        "type": action_type,
                        "matched_text": instruction[start:end],
                        "start": start,
                        "end": end,
                    }
                )

    matches.sort(key=lambda item: (item["start"], -(item["end"] - item["start"])))
    selected: list[dict[str, Any]] = []
    occupied_spans: list[tuple[int, int]] = []

    for match in matches:
        span = (match["start"], match["end"])
        if any(_spans_overlap(span, occupied) for occupied in occupied_spans):
            continue
        occupied_spans.append(span)
        selected.append(match)

    selected.sort(key=lambda item: item["start"])
    merged: list[dict[str, Any]] = []
    for match in selected:
        if (
            merged
            and merged[-1]["type"] == match["type"]
            and match["start"] - merged[-1]["end"] <= 2
        ):
            merged[-1]["end"] = match["end"]
            merged[-1]["matched_text"] = instruction[merged[-1]["start"] : merged[-1]["end"]]
            continue
        merged.append(match)

    return [
        {
            "order": index + 1,
            "type": match["type"],
            "matched_text": match["matched_text"],
        }
        for index, match in enumerate(merged)
    ]


def estimate_instruction_derived_actions(
    instruction_actions: list[dict[str, Any]],
    step_seconds: float = 1.0,
) -> list[dict[str, float]]:
    """Map parsed instruction actions to coarse dx/dy/dyaw pseudo-actions.

    dy is intentionally kept at 0.0 because lateral displacement is unreliable
    in the current human egocentric video setting. up/down are preserved in
    instruction_actions but are not forced into dx/dy/dyaw height changes.
    """
    actions: list[dict[str, float]] = []
    for index, instruction_action in enumerate(instruction_actions):
        action_type = str(instruction_action.get("type", "unknown"))
        rule = _instruction_action_rule(action_type)
        actions.append(
            {
                "t": round(index * step_seconds, 3),
                "dx": rule["dx"],
                "dy": 0.0,
                "dyaw": rule["dyaw"],
            }
        )
    return actions


def estimate_optical_flow_actions(
    navigation_clip: str | Path,
    sample_interval_seconds: float = 0.5,
) -> tuple[list[dict[str, float]], str]:
    """Estimate continuous pseudo-actions from video optical flow.

    The returned dx/dy/dyaw values are normalized video-based pseudo-actions:
    dx approximates forward motion intensity from flow magnitude, dy captures
    horizontal visual translation trend, and dyaw approximates left/right
    rotation from the difference between horizontal flow in the left and right
    image regions. These values are not ground-truth UAV odometry.
    """
    path = Path(navigation_clip)
    if not path.exists():
        return [], f"{OPTICAL_FLOW_ACTION_NOTE} Optical flow failed: clip not found."

    cap = cv2.VideoCapture(str(path))
    fps = cap.get(cv2.CAP_PROP_FPS)
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    if fps <= 0 or np.isnan(fps) or total_frames <= 1:
        cap.release()
        return [], f"{OPTICAL_FLOW_ACTION_NOTE} Optical flow failed: invalid video metadata."

    frame_step = max(1, int(round(fps * sample_interval_seconds)))
    frame_indices = list(range(0, total_frames, frame_step))
    if frame_indices[-1] != total_frames - 1:
        frame_indices.append(total_frames - 1)

    previous_gray: Any | None = None
    previous_index: int | None = None
    actions: list[dict[str, float]] = []

    for frame_index in frame_indices:
        cap.set(cv2.CAP_PROP_POS_FRAMES, frame_index)
        ret, frame = cap.read()
        if not ret:
            continue

        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        if previous_gray is None:
            previous_gray = gray
            previous_index = frame_index
            continue

        flow = cv2.calcOpticalFlowFarneback(
            previous_gray,
            gray,
            None,
            pyr_scale=0.5,
            levels=3,
            winsize=15,
            iterations=3,
            poly_n=5,
            poly_sigma=1.2,
            flags=0,
        )
        action = _flow_to_action(flow)
        t = (previous_index or 0) / fps
        actions.append(
            {
                "t": round(float(t), 3),
                "dx": action["dx"],
                "dy": action["dy"],
                "dyaw": action["dyaw"],
            }
        )

        previous_gray = gray
        previous_index = frame_index

    cap.release()

    if not actions:
        return [], f"{OPTICAL_FLOW_ACTION_NOTE} Optical flow failed: no valid frame pairs."

    return actions, OPTICAL_FLOW_ACTION_NOTE


def estimate_actions(
    action_mode: str,
    motion_type: str,
    clip_duration: float,
    navigation_clip: str | Path | None = None,
    instruction: str = "",
) -> tuple[list[dict[str, float]], str, str]:
    """Estimate actions and return actions, action_source, and action_note."""
    if action_mode == "heuristic_from_motion_type":
        return (
            estimate_heuristic_actions(motion_type=motion_type, clip_duration=clip_duration),
            "heuristic_pseudo_label",
            HEURISTIC_ACTION_NOTE,
        )
    if action_mode == "instruction_derived":
        instruction_actions = parse_instruction_actions(instruction)
        return (
            estimate_instruction_derived_actions(instruction_actions),
            "instruction_derived_pseudo_action",
            INSTRUCTION_ACTION_NOTE,
        )
    if action_mode == "optical_flow_baseline":
        if navigation_clip is None:
            return (
                [],
                "optical_flow_pseudo_label",
                f"{OPTICAL_FLOW_ACTION_NOTE} Optical flow failed: navigation_clip was not provided.",
            )
        try:
            actions, note = estimate_optical_flow_actions(navigation_clip)
        except Exception as exc:
            actions = []
            note = f"{OPTICAL_FLOW_ACTION_NOTE} Optical flow failed: {type(exc).__name__}: {exc}"
        return actions, "optical_flow_pseudo_label", note

    return estimate_empty_actions(), "empty", EMPTY_ACTION_NOTE


def _find_keyword_spans(text: str, keyword: str) -> list[tuple[int, int]]:
    lowered_keyword = keyword.lower()
    if lowered_keyword.isascii():
        pattern = r"(?<![A-Za-z])" + re.escape(lowered_keyword) + r"(?![A-Za-z])"
        return [(match.start(), match.end()) for match in re.finditer(pattern, text)]

    spans: list[tuple[int, int]] = []
    start = 0
    while True:
        index = text.find(lowered_keyword, start)
        if index == -1:
            break
        spans.append((index, index + len(lowered_keyword)))
        start = index + len(lowered_keyword)
    return spans


def _spans_overlap(span_a: tuple[int, int], span_b: tuple[int, int]) -> bool:
    return span_a[0] < span_b[1] and span_b[0] < span_a[1]


def _instruction_action_rule(action_type: str) -> dict[str, float]:
    if action_type == "forward":
        return {"dx": 0.3, "dyaw": 0.0}
    if action_type == "left_turn":
        return {"dx": 0.05, "dyaw": 0.25}
    if action_type == "right_turn":
        return {"dx": 0.05, "dyaw": -0.25}
    if action_type == "stop":
        return {"dx": 0.0, "dyaw": 0.0}
    if action_type in {"up", "down"}:
        return {"dx": 0.0, "dyaw": 0.0}
    return {"dx": 0.0, "dyaw": 0.0}


def _flow_to_action(flow: np.ndarray) -> dict[str, float]:
    height, width = flow.shape[:2]
    flow_x = flow[:, :, 0]
    flow_y = flow[:, :, 1]
    magnitude = np.sqrt(flow_x**2 + flow_y**2)

    scale = max(width, height, 1)
    dx = float(np.clip(np.mean(magnitude) / scale * 10.0, 0.0, 1.0))
    dy = float(np.clip(np.mean(flow_x) / width * 10.0, -1.0, 1.0))

    midpoint = max(1, width // 2)
    left_flow = float(np.mean(flow_x[:, :midpoint]))
    right_flow = float(np.mean(flow_x[:, midpoint:])) if midpoint < width else left_flow
    dyaw = float(np.clip((right_flow - left_flow) / width * 10.0, -1.0, 1.0))

    return {
        "dx": round(dx, 4),
        "dy": round(dy, 4),
        "dyaw": round(dyaw, 4),
    }


def _motion_rule(motion_type: str) -> dict[str, float]:
    if motion_type == "forward":
        return {"dx": 0.2, "dy": 0.0, "dyaw": 0.0}
    if motion_type == "left_turn":
        return {"dx": 0.0, "dy": 0.0, "dyaw": 0.15}
    if motion_type == "right_turn":
        return {"dx": 0.0, "dy": 0.0, "dyaw": -0.15}
    if motion_type == "forward_left":
        return {"dx": 0.15, "dy": 0.0, "dyaw": 0.08}
    if motion_type == "forward_right":
        return {"dx": 0.15, "dy": 0.0, "dyaw": -0.08}
    if motion_type == "stop":
        return {"dx": 0.0, "dy": 0.0, "dyaw": 0.0}
    if motion_type == "mixed":
        return {"dx": 0.1, "dy": 0.0, "dyaw": 0.0}
    return {"dx": 0.0, "dy": 0.0, "dyaw": 0.0}
